general {
    hide_cursor = true
}

background {
  monitor = 
  path=~/.local/share/backgrounds/lakeside.jpg
  blur_passes =3
}

animations {
  enabled = true 
}

label {
    text = LOCKED
    font_size = 90
    font_family =  Rubik Mono One

    halign = center
    valign = center
}


